/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_gestion (void)
{
  GtkWidget *window_gestion;
  GtkWidget *fixed4;
  GtkWidget *label_bienvenue;
  GtkWidget *label_total;
  GtkWidget *label_nombre_total;
  GtkWidget *label_niveau2;
  GtkWidget *label_niveau5;
  GtkWidget *label_niveau4;
  GtkWidget *label_niveau3;
  GtkWidget *label_niveau1;
  GtkWidget *label_nombre1;
  GtkWidget *label_nombre2;
  GtkWidget *label_nombre3;
  GtkWidget *label_nombre4;
  GtkWidget *label_nombre5;
  GtkWidget *image33;
  GtkWidget *button_ajouter_etudiant;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *label92;
  GtkWidget *image7;
  GtkWidget *button_afficher_liste;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *label94;
  GtkWidget *image9;
  GtkWidget *quitter1;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *label162;
  GtkWidget *image34;
  GtkWidget *image30;
  GtkWidget *image40;

  window_gestion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_gestion, 1163, 715);
  gtk_window_set_title (GTK_WINDOW (window_gestion), _("Gestion des \303\251tudiants"));
  gtk_window_set_position (GTK_WINDOW (window_gestion), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (window_gestion), FALSE);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window_gestion), fixed4);

  label_bienvenue = gtk_label_new (_("Bienvenue dans l'espace de gestion des \303\251tudiants"));
  gtk_widget_show (label_bienvenue);
  gtk_fixed_put (GTK_FIXED (fixed4), label_bienvenue, 285, 217);
  gtk_widget_set_size_request (label_bienvenue, 592, 50);

  label_total = gtk_label_new (_("Nombre total des \303\251tudiants:"));
  gtk_widget_show (label_total);
  gtk_fixed_put (GTK_FIXED (fixed4), label_total, 472, 274);
  gtk_widget_set_size_request (label_total, 198, 30);

  label_nombre_total = gtk_label_new ("");
  gtk_widget_show (label_nombre_total);
  gtk_fixed_put (GTK_FIXED (fixed4), label_nombre_total, 664, 274);
  gtk_widget_set_size_request (label_nombre_total, 40, 30);

  label_niveau2 = gtk_label_new (_("Deuxi\303\250me ann\303\251e:"));
  gtk_widget_show (label_niveau2);
  gtk_fixed_put (GTK_FIXED (fixed4), label_niveau2, 505, 328);
  gtk_widget_set_size_request (label_niveau2, 125, 30);

  label_niveau5 = gtk_label_new (_("Cinqui\303\250me ann\303\251e:"));
  gtk_widget_show (label_niveau5);
  gtk_fixed_put (GTK_FIXED (fixed4), label_niveau5, 507, 400);
  gtk_widget_set_size_request (label_niveau5, 125, 30);

  label_niveau4 = gtk_label_new (_("Quatri\303\250me ann\303\251e:"));
  gtk_widget_show (label_niveau4);
  gtk_fixed_put (GTK_FIXED (fixed4), label_niveau4, 507, 376);
  gtk_widget_set_size_request (label_niveau4, 125, 30);

  label_niveau3 = gtk_label_new (_("Troisi\303\250me ann\303\251e:"));
  gtk_widget_show (label_niveau3);
  gtk_fixed_put (GTK_FIXED (fixed4), label_niveau3, 506, 352);
  gtk_widget_set_size_request (label_niveau3, 121, 30);

  label_niveau1 = gtk_label_new (_("Premi\303\250re ann\303\251e:"));
  gtk_widget_show (label_niveau1);
  gtk_fixed_put (GTK_FIXED (fixed4), label_niveau1, 503, 304);
  gtk_widget_set_size_request (label_niveau1, 125, 30);

  label_nombre1 = gtk_label_new (_("0"));
  gtk_widget_show (label_nombre1);
  gtk_fixed_put (GTK_FIXED (fixed4), label_nombre1, 624, 304);
  gtk_widget_set_size_request (label_nombre1, 40, 30);

  label_nombre2 = gtk_label_new (_("0"));
  gtk_widget_show (label_nombre2);
  gtk_fixed_put (GTK_FIXED (fixed4), label_nombre2, 624, 328);
  gtk_widget_set_size_request (label_nombre2, 40, 30);

  label_nombre3 = gtk_label_new (_("0"));
  gtk_widget_show (label_nombre3);
  gtk_fixed_put (GTK_FIXED (fixed4), label_nombre3, 624, 352);
  gtk_widget_set_size_request (label_nombre3, 40, 30);

  label_nombre4 = gtk_label_new (_("0"));
  gtk_widget_show (label_nombre4);
  gtk_fixed_put (GTK_FIXED (fixed4), label_nombre4, 624, 376);
  gtk_widget_set_size_request (label_nombre4, 40, 30);

  label_nombre5 = gtk_label_new (_("0"));
  gtk_widget_show (label_nombre5);
  gtk_fixed_put (GTK_FIXED (fixed4), label_nombre5, 624, 400);
  gtk_widget_set_size_request (label_nombre5, 40, 30);

  image33 = create_pixmap (window_gestion, "foyer.jpg");
  gtk_widget_show (image33);
  gtk_fixed_put (GTK_FIXED (fixed4), image33, 288, 0);
  gtk_widget_set_size_request (image33, 592, 216);

  button_ajouter_etudiant = gtk_button_new ();
  gtk_widget_show (button_ajouter_etudiant);
  gtk_fixed_put (GTK_FIXED (fixed4), button_ajouter_etudiant, 476, 455);
  gtk_widget_set_size_request (button_ajouter_etudiant, 203, 50);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_ajouter_etudiant), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  label92 = gtk_label_new_with_mnemonic (_("Ajouter un \303\251tudiant"));
  gtk_widget_show (label92);
  gtk_box_pack_start (GTK_BOX (hbox7), label92, FALSE, FALSE, 9);

  image7 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 1);

  button_afficher_liste = gtk_button_new ();
  gtk_widget_show (button_afficher_liste);
  gtk_fixed_put (GTK_FIXED (fixed4), button_afficher_liste, 413, 534);
  gtk_widget_set_size_request (button_afficher_liste, 327, 50);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_afficher_liste), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  label94 = gtk_label_new_with_mnemonic (_("Afficher la liste  des \303\251tudiants"));
  gtk_widget_show (label94);
  gtk_box_pack_start (GTK_BOX (hbox9), label94, FALSE, FALSE, 6);

  image9 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 4);

  quitter1 = gtk_button_new ();
  gtk_widget_show (quitter1);
  gtk_fixed_put (GTK_FIXED (fixed4), quitter1, 534, 630);
  gtk_widget_set_size_request (quitter1, 90, 37);
  gtk_button_set_relief (GTK_BUTTON (quitter1), GTK_RELIEF_HALF);
  gtk_button_set_focus_on_click (GTK_BUTTON (quitter1), FALSE);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (quitter1), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  label162 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label162);
  gtk_box_pack_start (GTK_BOX (hbox27), label162, FALSE, FALSE, 5);

  image34 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image34);
  gtk_box_pack_start (GTK_BOX (hbox27), image34, FALSE, FALSE, 0);

  image30 = create_pixmap (window_gestion, "color1.jpg");
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed4), image30, 880, 0);
  gtk_widget_set_size_request (image30, 288, 720);

  image40 = create_pixmap (window_gestion, "color1.jpg");
  gtk_widget_show (image40);
  gtk_fixed_put (GTK_FIXED (fixed4), image40, 0, 0);
  gtk_widget_set_size_request (image40, 288, 720);

  g_signal_connect ((gpointer) window_gestion, "show",
                    G_CALLBACK (on_window_gestion_show),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter_etudiant, "clicked",
                    G_CALLBACK (on_button_ajouter_etudiant_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_afficher_liste, "clicked",
                    G_CALLBACK (on_button_afficher_liste_clicked),
                    NULL);
  g_signal_connect ((gpointer) quitter1, "clicked",
                    G_CALLBACK (on_quitter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_gestion, window_gestion, "window_gestion");
  GLADE_HOOKUP_OBJECT (window_gestion, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window_gestion, label_bienvenue, "label_bienvenue");
  GLADE_HOOKUP_OBJECT (window_gestion, label_total, "label_total");
  GLADE_HOOKUP_OBJECT (window_gestion, label_nombre_total, "label_nombre_total");
  GLADE_HOOKUP_OBJECT (window_gestion, label_niveau2, "label_niveau2");
  GLADE_HOOKUP_OBJECT (window_gestion, label_niveau5, "label_niveau5");
  GLADE_HOOKUP_OBJECT (window_gestion, label_niveau4, "label_niveau4");
  GLADE_HOOKUP_OBJECT (window_gestion, label_niveau3, "label_niveau3");
  GLADE_HOOKUP_OBJECT (window_gestion, label_niveau1, "label_niveau1");
  GLADE_HOOKUP_OBJECT (window_gestion, label_nombre1, "label_nombre1");
  GLADE_HOOKUP_OBJECT (window_gestion, label_nombre2, "label_nombre2");
  GLADE_HOOKUP_OBJECT (window_gestion, label_nombre3, "label_nombre3");
  GLADE_HOOKUP_OBJECT (window_gestion, label_nombre4, "label_nombre4");
  GLADE_HOOKUP_OBJECT (window_gestion, label_nombre5, "label_nombre5");
  GLADE_HOOKUP_OBJECT (window_gestion, image33, "image33");
  GLADE_HOOKUP_OBJECT (window_gestion, button_ajouter_etudiant, "button_ajouter_etudiant");
  GLADE_HOOKUP_OBJECT (window_gestion, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window_gestion, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window_gestion, label92, "label92");
  GLADE_HOOKUP_OBJECT (window_gestion, image7, "image7");
  GLADE_HOOKUP_OBJECT (window_gestion, button_afficher_liste, "button_afficher_liste");
  GLADE_HOOKUP_OBJECT (window_gestion, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window_gestion, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window_gestion, label94, "label94");
  GLADE_HOOKUP_OBJECT (window_gestion, image9, "image9");
  GLADE_HOOKUP_OBJECT (window_gestion, quitter1, "quitter1");
  GLADE_HOOKUP_OBJECT (window_gestion, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (window_gestion, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (window_gestion, label162, "label162");
  GLADE_HOOKUP_OBJECT (window_gestion, image34, "image34");
  GLADE_HOOKUP_OBJECT (window_gestion, image30, "image30");
  GLADE_HOOKUP_OBJECT (window_gestion, image40, "image40");

  return window_gestion;
}

GtkWidget*
create_window_ajout (void)
{
  GtkWidget *window_ajout;
  GtkWidget *fixed10;
  GtkWidget *entry_nom;
  GtkWidget *entry_prenom;
  GtkWidget *entry_id;
  GtkWidget *entry_adresse;
  GtkWidget *entry_telephone;
  GtkWidget *entry_mail;
  GtkObject *spinbutton_niveau_adj;
  GtkWidget *spinbutton_niveau;
  GtkWidget *entry_numero_chambre;
  GtkWidget *entry_naissance;
  GtkWidget *entry_debut_sejour;
  GtkWidget *entry_fin_sejour;
  GtkWidget *label_prenom;
  GtkWidget *label_niveau;
  GtkWidget *label_sexe;
  GtkWidget *label_telephone;
  GtkWidget *label_mail;
  GtkWidget *label_adresse;
  GtkWidget *label_numero_chambre;
  GtkWidget *label_id;
  GtkWidget *label_remplir;
  GtkWidget *label_fin_sejour;
  GtkWidget *label147;
  GtkWidget *label_nom;
  GtkWidget *label_naissance;
  GtkWidget *label_type_chambre;
  GtkWidget *label_debut_sejour;
  GtkWidget *label145;
  GtkWidget *label146;
  GtkWidget *combobox_type_chambre;
  GtkWidget *radiobutton_homme;
  GSList *radiobutton_homme_group = NULL;
  GtkWidget *radiobutton_femme;
  GtkWidget *label_ajoute;
  GtkWidget *button_ajouter;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *label66;
  GtkWidget *image4;
  GtkWidget *button_afficher_ajout;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *label143;
  GtkWidget *image21;
  GtkWidget *button_retour_ajout;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image19;
  GtkWidget *label141;
  GtkWidget *quitter2;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *label163;
  GtkWidget *image35;
  GtkWidget *label_prenom_manquant;
  GtkWidget *label_exist_ajout;
  GtkWidget *label_id_manquant;
  GtkWidget *label_niveau_manquant;
  GtkWidget *label_naissance_manquant;
  GtkWidget *label_sexe_manquant;
  GtkWidget *label_telephone_manquant;
  GtkWidget *label_mail_manquant;
  GtkWidget *label_adresse_manquant;
  GtkWidget *label_type_chambre_manquant;
  GtkWidget *label_numero_chambre_manquant;
  GtkWidget *label_debut_sejour_manquant;
  GtkWidget *label_fin_sejour_manquant;
  GtkWidget *label_nom_manquant;

  window_ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_ajout, 1163, 715);
  gtk_window_set_title (GTK_WINDOW (window_ajout), _("Ajout d'un \303\251tudiant"));
  gtk_window_set_position (GTK_WINDOW (window_ajout), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (window_ajout), FALSE);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (window_ajout), fixed10);

  entry_nom = gtk_entry_new ();
  gtk_widget_show (entry_nom);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_nom, 518, 56);
  gtk_widget_set_size_request (entry_nom, 304, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom), 8226);

  entry_prenom = gtk_entry_new ();
  gtk_widget_show (entry_prenom);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_prenom, 518, 96);
  gtk_widget_set_size_request (entry_prenom, 304, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom), 8226);

  entry_id = gtk_entry_new ();
  gtk_widget_show (entry_id);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_id, 518, 136);
  gtk_widget_set_size_request (entry_id, 304, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id), 8226);

  entry_adresse = gtk_entry_new ();
  gtk_widget_show (entry_adresse);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_adresse, 518, 376);
  gtk_widget_set_size_request (entry_adresse, 304, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_adresse), 8226);

  entry_telephone = gtk_entry_new ();
  gtk_widget_show (entry_telephone);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_telephone, 518, 296);
  gtk_widget_set_size_request (entry_telephone, 304, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_telephone), 8226);

  entry_mail = gtk_entry_new ();
  gtk_widget_show (entry_mail);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_mail, 518, 336);
  gtk_widget_set_size_request (entry_mail, 304, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mail), 8226);

  spinbutton_niveau_adj = gtk_adjustment_new (1, 1, 5, 1, 1, 0);
  spinbutton_niveau = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_niveau_adj), 1, 0);
  gtk_widget_show (spinbutton_niveau);
  gtk_fixed_put (GTK_FIXED (fixed10), spinbutton_niveau, 518, 176);
  gtk_widget_set_size_request (spinbutton_niveau, 44, 30);

  entry_numero_chambre = gtk_entry_new ();
  gtk_widget_show (entry_numero_chambre);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_numero_chambre, 518, 456);
  gtk_widget_set_size_request (entry_numero_chambre, 304, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_numero_chambre), 8226);

  entry_naissance = gtk_entry_new ();
  gtk_widget_show (entry_naissance);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_naissance, 518, 216);
  gtk_widget_set_size_request (entry_naissance, 177, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_naissance), 8226);

  entry_debut_sejour = gtk_entry_new ();
  gtk_widget_show (entry_debut_sejour);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_debut_sejour, 518, 496);
  gtk_widget_set_size_request (entry_debut_sejour, 177, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_debut_sejour), 8226);

  entry_fin_sejour = gtk_entry_new ();
  gtk_widget_show (entry_fin_sejour);
  gtk_fixed_put (GTK_FIXED (fixed10), entry_fin_sejour, 518, 536);
  gtk_widget_set_size_request (entry_fin_sejour, 177, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_fin_sejour), 8226);

  label_prenom = gtk_label_new (_("Pr\303\251nom:"));
  gtk_widget_show (label_prenom);
  gtk_fixed_put (GTK_FIXED (fixed10), label_prenom, 350, 96);
  gtk_widget_set_size_request (label_prenom, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_prenom), TRUE);

  label_niveau = gtk_label_new (_("Niveau:"));
  gtk_widget_show (label_niveau);
  gtk_fixed_put (GTK_FIXED (fixed10), label_niveau, 350, 176);
  gtk_widget_set_size_request (label_niveau, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_niveau), TRUE);

  label_sexe = gtk_label_new (_("Sexe:"));
  gtk_widget_show (label_sexe);
  gtk_fixed_put (GTK_FIXED (fixed10), label_sexe, 350, 256);
  gtk_widget_set_size_request (label_sexe, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_sexe), TRUE);

  label_telephone = gtk_label_new (_("T\303\251l\303\251phone"));
  gtk_widget_show (label_telephone);
  gtk_fixed_put (GTK_FIXED (fixed10), label_telephone, 350, 296);
  gtk_widget_set_size_request (label_telephone, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_telephone), TRUE);

  label_mail = gtk_label_new (_("Mail:"));
  gtk_widget_show (label_mail);
  gtk_fixed_put (GTK_FIXED (fixed10), label_mail, 350, 336);
  gtk_widget_set_size_request (label_mail, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_mail), TRUE);

  label_adresse = gtk_label_new (_("Adresse:"));
  gtk_widget_show (label_adresse);
  gtk_fixed_put (GTK_FIXED (fixed10), label_adresse, 350, 376);
  gtk_widget_set_size_request (label_adresse, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_adresse), TRUE);

  label_numero_chambre = gtk_label_new (_("Num\303\251ro de chambre:"));
  gtk_widget_show (label_numero_chambre);
  gtk_fixed_put (GTK_FIXED (fixed10), label_numero_chambre, 350, 456);
  gtk_widget_set_size_request (label_numero_chambre, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_numero_chambre), TRUE);

  label_id = gtk_label_new (_("ID:"));
  gtk_widget_show (label_id);
  gtk_fixed_put (GTK_FIXED (fixed10), label_id, 350, 136);
  gtk_widget_set_size_request (label_id, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_id), TRUE);

  label_remplir = gtk_label_new (_("Veuillez remplir le formulaire suivant pour ajouter un \303\251tudiant :"));
  gtk_widget_show (label_remplir);
  gtk_fixed_put (GTK_FIXED (fixed10), label_remplir, 0, 2);
  gtk_widget_set_size_request (label_remplir, 1163, 38);

  label_fin_sejour = gtk_label_new (_("Date de fin de s\303\251jour:"));
  gtk_widget_show (label_fin_sejour);
  gtk_fixed_put (GTK_FIXED (fixed10), label_fin_sejour, 350, 536);
  gtk_widget_set_size_request (label_fin_sejour, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_fin_sejour), TRUE);

  label147 = gtk_label_new (_("jj/mm/aaaa"));
  gtk_widget_show (label147);
  gtk_fixed_put (GTK_FIXED (fixed10), label147, 704, 496);
  gtk_widget_set_size_request (label147, 122, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label147), TRUE);

  label_nom = gtk_label_new (_("Nom:"));
  gtk_widget_show (label_nom);
  gtk_fixed_put (GTK_FIXED (fixed10), label_nom, 350, 56);
  gtk_widget_set_size_request (label_nom, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_nom), TRUE);

  label_naissance = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (label_naissance);
  gtk_fixed_put (GTK_FIXED (fixed10), label_naissance, 350, 216);
  gtk_widget_set_size_request (label_naissance, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_naissance), TRUE);

  label_type_chambre = gtk_label_new (_("Type de chambre:"));
  gtk_widget_show (label_type_chambre);
  gtk_fixed_put (GTK_FIXED (fixed10), label_type_chambre, 350, 416);
  gtk_widget_set_size_request (label_type_chambre, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_type_chambre), TRUE);

  label_debut_sejour = gtk_label_new (_("Date de d\303\251but de s\303\251jour:"));
  gtk_widget_show (label_debut_sejour);
  gtk_fixed_put (GTK_FIXED (fixed10), label_debut_sejour, 350, 496);
  gtk_widget_set_size_request (label_debut_sejour, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_debut_sejour), TRUE);

  label145 = gtk_label_new (_("jj/mm/aaaa"));
  gtk_widget_show (label145);
  gtk_fixed_put (GTK_FIXED (fixed10), label145, 704, 216);
  gtk_widget_set_size_request (label145, 122, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label145), TRUE);

  label146 = gtk_label_new (_("jj/mm/aaaa"));
  gtk_widget_show (label146);
  gtk_fixed_put (GTK_FIXED (fixed10), label146, 704, 536);
  gtk_widget_set_size_request (label146, 122, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label146), TRUE);

  combobox_type_chambre = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_type_chambre);
  gtk_fixed_put (GTK_FIXED (fixed10), combobox_type_chambre, 518, 416);
  gtk_widget_set_size_request (combobox_type_chambre, 304, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_type_chambre), _("Chambre_\303\240_1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_type_chambre), _("Chambre_\303\240_2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_type_chambre), _("Chambre_\303\240_3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_type_chambre), _("Chambre_\303\240_4"));

  radiobutton_homme = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (radiobutton_homme);
  gtk_fixed_put (GTK_FIXED (fixed10), radiobutton_homme, 520, 256);
  gtk_widget_set_size_request (radiobutton_homme, 85, 30);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_homme), radiobutton_homme_group);
  radiobutton_homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_homme));

  radiobutton_femme = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (radiobutton_femme);
  gtk_fixed_put (GTK_FIXED (fixed10), radiobutton_femme, 624, 256);
  gtk_widget_set_size_request (radiobutton_femme, 85, 30);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_femme), radiobutton_homme_group);
  radiobutton_homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_femme));

  label_ajoute = gtk_label_new ("");
  gtk_widget_show (label_ajoute);
  gtk_fixed_put (GTK_FIXED (fixed10), label_ajoute, 536, 624);
  gtk_widget_set_size_request (label_ajoute, 130, 30);

  button_ajouter = gtk_button_new ();
  gtk_widget_show (button_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed10), button_ajouter, 555, 587);
  gtk_widget_set_size_request (button_ajouter, 100, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_ajouter), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  label66 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox4), label66, FALSE, FALSE, 0);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 1);

  button_afficher_ajout = gtk_button_new ();
  gtk_widget_show (button_afficher_ajout);
  gtk_fixed_put (GTK_FIXED (fixed10), button_afficher_ajout, 565, 655);
  gtk_widget_set_size_request (button_afficher_ajout, 84, 35);
  gtk_button_set_relief (GTK_BUTTON (button_afficher_ajout), GTK_RELIEF_HALF);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button_afficher_ajout), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  label143 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label143);
  gtk_box_pack_start (GTK_BOX (hbox19), label143, FALSE, FALSE, 0);

  image21 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox19), image21, FALSE, FALSE, 1);

  button_retour_ajout = gtk_button_new ();
  gtk_widget_show (button_retour_ajout);
  gtk_fixed_put (GTK_FIXED (fixed10), button_retour_ajout, 365, 655);
  gtk_widget_set_size_request (button_retour_ajout, 84, 35);
  gtk_button_set_relief (GTK_BUTTON (button_retour_ajout), GTK_RELIEF_HALF);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button_retour_ajout), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image19 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox17), image19, FALSE, FALSE, 1);

  label141 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label141);
  gtk_box_pack_start (GTK_BOX (hbox17), label141, FALSE, FALSE, 0);

  quitter2 = gtk_button_new ();
  gtk_widget_show (quitter2);
  gtk_fixed_put (GTK_FIXED (fixed10), quitter2, 749, 655);
  gtk_widget_set_size_request (quitter2, 79, 35);
  gtk_button_set_relief (GTK_BUTTON (quitter2), GTK_RELIEF_HALF);
  gtk_button_set_focus_on_click (GTK_BUTTON (quitter2), FALSE);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (quitter2), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  label163 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label163);
  gtk_box_pack_start (GTK_BOX (hbox28), label163, FALSE, FALSE, 0);

  image35 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox28), image35, FALSE, FALSE, 0);

  label_prenom_manquant = gtk_label_new ("");
  gtk_widget_show (label_prenom_manquant);
  gtk_fixed_put (GTK_FIXED (fixed10), label_prenom_manquant, 824, 96);
  gtk_widget_set_size_request (label_prenom_manquant, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_prenom_manquant), TRUE);

  label_exist_ajout = gtk_label_new ("");
  gtk_widget_show (label_exist_ajout);
  gtk_fixed_put (GTK_FIXED (fixed10), label_exist_ajout, 824, 136);
  gtk_widget_set_size_request (label_exist_ajout, 106, 30);

  label_id_manquant = gtk_label_new ("");
  gtk_widget_show (label_id_manquant);
  gtk_fixed_put (GTK_FIXED (fixed10), label_id_manquant, 824, 136);
  gtk_widget_set_size_request (label_id_manquant, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_id_manquant), TRUE);

  label_niveau_manquant = gtk_label_new ("");
  gtk_widget_show (label_niveau_manquant);
  gtk_fixed_put (GTK_FIXED (fixed10), label_niveau_manquant, 824, 176);
  gtk_widget_set_size_request (label_niveau_manquant, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_niveau_manquant), TRUE);

  label_naissance_manquant = gtk_label_new ("");
  gtk_widget_show (label_naissance_manquant);
  gtk_fixed_put (GTK_FIXED (fixed10), label_naissance_manquant, 824, 216);
  gtk_widget_set_size_request (label_naissance_manquant, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_naissance_manquant), TRUE);

  label_sexe_manquant = gtk_label_new ("");
  gtk_widget_show (label_sexe_manquant);
  gtk_fixed_put (GTK_FIXED (fixed10), label_sexe_manquant, 824, 256);
  gtk_widget_set_size_request (label_sexe_manquant, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_sexe_manquant), TRUE);

  label_telephone_manquant = gtk_label_new ("");
  gtk_widget_show (label_telephone_manquant);
  gtk_fixed_put (GTK_FIXED (fixed10), label_telephone_manquant, 824, 296);
  gtk_widget_set_size_request (label_telephone_manquant, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_telephone_manquant), TRUE);

  label_mail_manquant = gtk_label_new ("");
  gtk_widget_show (label_mail_manquant);
  gtk_fixed_put (GTK_FIXED (fixed10), label_mail_manquant, 824, 336);
  gtk_widget_set_size_request (label_mail_manquant, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_mail_manquant), TRUE);

  label_adresse_manquant = gtk_label_new ("");
  gtk_widget_show (label_adresse_manquant);
  gtk_fixed_put (GTK_FIXED (fixed10), label_adresse_manquant, 824, 376);
  gtk_widget_set_size_request (label_adresse_manquant, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_adresse_manquant), TRUE);

  label_type_chambre_manquant = gtk_label_new ("");
  gtk_widget_show (label_type_chambre_manquant);
  gtk_fixed_put (GTK_FIXED (fixed10), label_type_chambre_manquant, 824, 416);
  gtk_widget_set_size_request (label_type_chambre_manquant, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_type_chambre_manquant), TRUE);

  label_numero_chambre_manquant = gtk_label_new ("");
  gtk_widget_show (label_numero_chambre_manquant);
  gtk_fixed_put (GTK_FIXED (fixed10), label_numero_chambre_manquant, 824, 456);
  gtk_widget_set_size_request (label_numero_chambre_manquant, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_numero_chambre_manquant), TRUE);

  label_debut_sejour_manquant = gtk_label_new ("");
  gtk_widget_show (label_debut_sejour_manquant);
  gtk_fixed_put (GTK_FIXED (fixed10), label_debut_sejour_manquant, 824, 496);
  gtk_widget_set_size_request (label_debut_sejour_manquant, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_debut_sejour_manquant), TRUE);

  label_fin_sejour_manquant = gtk_label_new ("");
  gtk_widget_show (label_fin_sejour_manquant);
  gtk_fixed_put (GTK_FIXED (fixed10), label_fin_sejour_manquant, 824, 536);
  gtk_widget_set_size_request (label_fin_sejour_manquant, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_fin_sejour_manquant), TRUE);

  label_nom_manquant = gtk_label_new ("");
  gtk_widget_show (label_nom_manquant);
  gtk_fixed_put (GTK_FIXED (fixed10), label_nom_manquant, 824, 56);
  gtk_widget_set_size_request (label_nom_manquant, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_nom_manquant), TRUE);

  g_signal_connect ((gpointer) button_ajouter, "clicked",
                    G_CALLBACK (on_button_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_afficher_ajout, "clicked",
                    G_CALLBACK (on_button_afficher_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_ajout, "clicked",
                    G_CALLBACK (on_button_retour_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) quitter2, "clicked",
                    G_CALLBACK (on_quitter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_ajout, window_ajout, "window_ajout");
  GLADE_HOOKUP_OBJECT (window_ajout, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (window_ajout, entry_nom, "entry_nom");
  GLADE_HOOKUP_OBJECT (window_ajout, entry_prenom, "entry_prenom");
  GLADE_HOOKUP_OBJECT (window_ajout, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (window_ajout, entry_adresse, "entry_adresse");
  GLADE_HOOKUP_OBJECT (window_ajout, entry_telephone, "entry_telephone");
  GLADE_HOOKUP_OBJECT (window_ajout, entry_mail, "entry_mail");
  GLADE_HOOKUP_OBJECT (window_ajout, spinbutton_niveau, "spinbutton_niveau");
  GLADE_HOOKUP_OBJECT (window_ajout, entry_numero_chambre, "entry_numero_chambre");
  GLADE_HOOKUP_OBJECT (window_ajout, entry_naissance, "entry_naissance");
  GLADE_HOOKUP_OBJECT (window_ajout, entry_debut_sejour, "entry_debut_sejour");
  GLADE_HOOKUP_OBJECT (window_ajout, entry_fin_sejour, "entry_fin_sejour");
  GLADE_HOOKUP_OBJECT (window_ajout, label_prenom, "label_prenom");
  GLADE_HOOKUP_OBJECT (window_ajout, label_niveau, "label_niveau");
  GLADE_HOOKUP_OBJECT (window_ajout, label_sexe, "label_sexe");
  GLADE_HOOKUP_OBJECT (window_ajout, label_telephone, "label_telephone");
  GLADE_HOOKUP_OBJECT (window_ajout, label_mail, "label_mail");
  GLADE_HOOKUP_OBJECT (window_ajout, label_adresse, "label_adresse");
  GLADE_HOOKUP_OBJECT (window_ajout, label_numero_chambre, "label_numero_chambre");
  GLADE_HOOKUP_OBJECT (window_ajout, label_id, "label_id");
  GLADE_HOOKUP_OBJECT (window_ajout, label_remplir, "label_remplir");
  GLADE_HOOKUP_OBJECT (window_ajout, label_fin_sejour, "label_fin_sejour");
  GLADE_HOOKUP_OBJECT (window_ajout, label147, "label147");
  GLADE_HOOKUP_OBJECT (window_ajout, label_nom, "label_nom");
  GLADE_HOOKUP_OBJECT (window_ajout, label_naissance, "label_naissance");
  GLADE_HOOKUP_OBJECT (window_ajout, label_type_chambre, "label_type_chambre");
  GLADE_HOOKUP_OBJECT (window_ajout, label_debut_sejour, "label_debut_sejour");
  GLADE_HOOKUP_OBJECT (window_ajout, label145, "label145");
  GLADE_HOOKUP_OBJECT (window_ajout, label146, "label146");
  GLADE_HOOKUP_OBJECT (window_ajout, combobox_type_chambre, "combobox_type_chambre");
  GLADE_HOOKUP_OBJECT (window_ajout, radiobutton_homme, "radiobutton_homme");
  GLADE_HOOKUP_OBJECT (window_ajout, radiobutton_femme, "radiobutton_femme");
  GLADE_HOOKUP_OBJECT (window_ajout, label_ajoute, "label_ajoute");
  GLADE_HOOKUP_OBJECT (window_ajout, button_ajouter, "button_ajouter");
  GLADE_HOOKUP_OBJECT (window_ajout, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window_ajout, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window_ajout, label66, "label66");
  GLADE_HOOKUP_OBJECT (window_ajout, image4, "image4");
  GLADE_HOOKUP_OBJECT (window_ajout, button_afficher_ajout, "button_afficher_ajout");
  GLADE_HOOKUP_OBJECT (window_ajout, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window_ajout, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window_ajout, label143, "label143");
  GLADE_HOOKUP_OBJECT (window_ajout, image21, "image21");
  GLADE_HOOKUP_OBJECT (window_ajout, button_retour_ajout, "button_retour_ajout");
  GLADE_HOOKUP_OBJECT (window_ajout, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window_ajout, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window_ajout, image19, "image19");
  GLADE_HOOKUP_OBJECT (window_ajout, label141, "label141");
  GLADE_HOOKUP_OBJECT (window_ajout, quitter2, "quitter2");
  GLADE_HOOKUP_OBJECT (window_ajout, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (window_ajout, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (window_ajout, label163, "label163");
  GLADE_HOOKUP_OBJECT (window_ajout, image35, "image35");
  GLADE_HOOKUP_OBJECT (window_ajout, label_prenom_manquant, "label_prenom_manquant");
  GLADE_HOOKUP_OBJECT (window_ajout, label_exist_ajout, "label_exist_ajout");
  GLADE_HOOKUP_OBJECT (window_ajout, label_id_manquant, "label_id_manquant");
  GLADE_HOOKUP_OBJECT (window_ajout, label_niveau_manquant, "label_niveau_manquant");
  GLADE_HOOKUP_OBJECT (window_ajout, label_naissance_manquant, "label_naissance_manquant");
  GLADE_HOOKUP_OBJECT (window_ajout, label_sexe_manquant, "label_sexe_manquant");
  GLADE_HOOKUP_OBJECT (window_ajout, label_telephone_manquant, "label_telephone_manquant");
  GLADE_HOOKUP_OBJECT (window_ajout, label_mail_manquant, "label_mail_manquant");
  GLADE_HOOKUP_OBJECT (window_ajout, label_adresse_manquant, "label_adresse_manquant");
  GLADE_HOOKUP_OBJECT (window_ajout, label_type_chambre_manquant, "label_type_chambre_manquant");
  GLADE_HOOKUP_OBJECT (window_ajout, label_numero_chambre_manquant, "label_numero_chambre_manquant");
  GLADE_HOOKUP_OBJECT (window_ajout, label_debut_sejour_manquant, "label_debut_sejour_manquant");
  GLADE_HOOKUP_OBJECT (window_ajout, label_fin_sejour_manquant, "label_fin_sejour_manquant");
  GLADE_HOOKUP_OBJECT (window_ajout, label_nom_manquant, "label_nom_manquant");

  return window_ajout;
}

GtkWidget*
create_window_modification (void)
{
  GtkWidget *window_modification;
  GtkWidget *fixed3;
  GtkWidget *entry_nom2;
  GtkWidget *entry_prenom2;
  GtkWidget *entry_id2;
  GtkWidget *entry_adresse2;
  GtkWidget *entry_telephone2;
  GtkWidget *entry_mail2;
  GtkObject *spinbutton_niveau2_adj;
  GtkWidget *spinbutton_niveau2;
  GtkWidget *entry_numero_chambre2;
  GtkWidget *entry_debut_sejour2;
  GtkWidget *entry_fin_sejour2;
  GtkWidget *entry_naissance2;
  GtkWidget *label_remplir_modification;
  GtkWidget *label_fin_sejour2;
  GtkWidget *label_debut_sejour2;
  GtkWidget *label_numero_chambre2;
  GtkWidget *label_type_chambre2;
  GtkWidget *label_adresse2;
  GtkWidget *label_mail2;
  GtkWidget *label_telephone2;
  GtkWidget *label_sexe2;
  GtkWidget *label_naissance2;
  GtkWidget *label_niveau2;
  GtkWidget *label_id2;
  GtkWidget *label_prenom2;
  GtkWidget *label_nom2;
  GtkWidget *label148;
  GtkWidget *combobox_type_chambre2;
  GtkWidget *label149;
  GtkWidget *radiobutton_homme2;
  GSList *radiobutton_homme2_group = NULL;
  GtkWidget *radiobutton_femme2;
  GtkWidget *label150;
  GtkWidget *button_afficher_modification;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *label79;
  GtkWidget *image6;
  GtkWidget *button_retour_modification;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label78;
  GtkWidget *label_modifie;
  GtkWidget *quitter3;
  GtkWidget *alignment29;
  GtkWidget *hbox29;
  GtkWidget *label166;
  GtkWidget *image36;
  GtkWidget *label_mail_manquant2;
  GtkWidget *label_adresse_manquant2;
  GtkWidget *label_type_chambre_manquant2;
  GtkWidget *label_numero_chambre_manquant2;
  GtkWidget *label_debut_sejour_manquant2;
  GtkWidget *label_fin_sejour_manquant2;
  GtkWidget *label_existe_modification;
  GtkWidget *label_nom_manquant2;
  GtkWidget *label_prenom_manquant2;
  GtkWidget *label_id_manquant2;
  GtkWidget *label_niveau_manquant2;
  GtkWidget *label_naissance_manquant2;
  GtkWidget *label_sexe_manquant2;
  GtkWidget *label_telephone_manquant2;
  GtkWidget *button_modifier;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *label144;
  GtkWidget *image22;
  GtkWidget *label_confirmer;
  GtkWidget *checkbutton1;

  window_modification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_modification, 1163, 715);
  gtk_window_set_title (GTK_WINDOW (window_modification), _("Modification"));
  gtk_window_set_position (GTK_WINDOW (window_modification), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (window_modification), FALSE);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window_modification), fixed3);

  entry_nom2 = gtk_entry_new ();
  gtk_widget_show (entry_nom2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_nom2, 518, 56);
  gtk_widget_set_size_request (entry_nom2, 304, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom2), 8226);

  entry_prenom2 = gtk_entry_new ();
  gtk_widget_show (entry_prenom2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_prenom2, 518, 96);
  gtk_widget_set_size_request (entry_prenom2, 304, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_prenom2), 8226);

  entry_id2 = gtk_entry_new ();
  gtk_widget_show (entry_id2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_id2, 518, 136);
  gtk_widget_set_size_request (entry_id2, 304, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id2), 8226);

  entry_adresse2 = gtk_entry_new ();
  gtk_widget_show (entry_adresse2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_adresse2, 518, 376);
  gtk_widget_set_size_request (entry_adresse2, 304, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_adresse2), 8226);

  entry_telephone2 = gtk_entry_new ();
  gtk_widget_show (entry_telephone2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_telephone2, 518, 296);
  gtk_widget_set_size_request (entry_telephone2, 304, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_telephone2), 8226);

  entry_mail2 = gtk_entry_new ();
  gtk_widget_show (entry_mail2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_mail2, 518, 336);
  gtk_widget_set_size_request (entry_mail2, 304, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mail2), 8226);

  spinbutton_niveau2_adj = gtk_adjustment_new (1, 1, 5, 1, 1, 0);
  spinbutton_niveau2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_niveau2_adj), 1, 0);
  gtk_widget_show (spinbutton_niveau2);
  gtk_fixed_put (GTK_FIXED (fixed3), spinbutton_niveau2, 518, 176);
  gtk_widget_set_size_request (spinbutton_niveau2, 44, 30);

  entry_numero_chambre2 = gtk_entry_new ();
  gtk_widget_show (entry_numero_chambre2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_numero_chambre2, 518, 456);
  gtk_widget_set_size_request (entry_numero_chambre2, 304, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_numero_chambre2), 8226);

  entry_debut_sejour2 = gtk_entry_new ();
  gtk_widget_show (entry_debut_sejour2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_debut_sejour2, 518, 496);
  gtk_widget_set_size_request (entry_debut_sejour2, 177, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_debut_sejour2), 8226);

  entry_fin_sejour2 = gtk_entry_new ();
  gtk_widget_show (entry_fin_sejour2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_fin_sejour2, 518, 536);
  gtk_widget_set_size_request (entry_fin_sejour2, 177, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_fin_sejour2), 8226);

  entry_naissance2 = gtk_entry_new ();
  gtk_widget_show (entry_naissance2);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_naissance2, 518, 216);
  gtk_widget_set_size_request (entry_naissance2, 177, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_naissance2), 8226);

  label_remplir_modification = gtk_label_new (_("Veuillez introduire les information \303\240 modifier :"));
  gtk_widget_show (label_remplir_modification);
  gtk_fixed_put (GTK_FIXED (fixed3), label_remplir_modification, 0, 2);
  gtk_widget_set_size_request (label_remplir_modification, 1163, 38);
  gtk_label_set_justify (GTK_LABEL (label_remplir_modification), GTK_JUSTIFY_CENTER);

  label_fin_sejour2 = gtk_label_new (_("Date de fin de s\303\251jour:"));
  gtk_widget_show (label_fin_sejour2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_fin_sejour2, 350, 536);
  gtk_widget_set_size_request (label_fin_sejour2, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_fin_sejour2), TRUE);

  label_debut_sejour2 = gtk_label_new (_("Date de d\303\251but de s\303\251jour:"));
  gtk_widget_show (label_debut_sejour2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_debut_sejour2, 350, 496);
  gtk_widget_set_size_request (label_debut_sejour2, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_debut_sejour2), TRUE);

  label_numero_chambre2 = gtk_label_new (_("Num\303\251ro de chambre:"));
  gtk_widget_show (label_numero_chambre2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_numero_chambre2, 350, 456);
  gtk_widget_set_size_request (label_numero_chambre2, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_numero_chambre2), TRUE);

  label_type_chambre2 = gtk_label_new (_("Type de chambre:"));
  gtk_widget_show (label_type_chambre2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_type_chambre2, 350, 416);
  gtk_widget_set_size_request (label_type_chambre2, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_type_chambre2), TRUE);

  label_adresse2 = gtk_label_new (_("Adresse:"));
  gtk_widget_show (label_adresse2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_adresse2, 350, 376);
  gtk_widget_set_size_request (label_adresse2, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_adresse2), TRUE);

  label_mail2 = gtk_label_new (_("Mail:"));
  gtk_widget_show (label_mail2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_mail2, 350, 336);
  gtk_widget_set_size_request (label_mail2, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_mail2), TRUE);

  label_telephone2 = gtk_label_new (_("T\303\251l\303\251phone"));
  gtk_widget_show (label_telephone2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_telephone2, 350, 296);
  gtk_widget_set_size_request (label_telephone2, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_telephone2), TRUE);

  label_sexe2 = gtk_label_new (_("Sexe:"));
  gtk_widget_show (label_sexe2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_sexe2, 350, 256);
  gtk_widget_set_size_request (label_sexe2, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_sexe2), TRUE);

  label_naissance2 = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (label_naissance2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_naissance2, 350, 216);
  gtk_widget_set_size_request (label_naissance2, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_naissance2), TRUE);

  label_niveau2 = gtk_label_new (_("Niveau:"));
  gtk_widget_show (label_niveau2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_niveau2, 350, 176);
  gtk_widget_set_size_request (label_niveau2, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_niveau2), TRUE);

  label_id2 = gtk_label_new (_("ID:"));
  gtk_widget_show (label_id2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_id2, 350, 136);
  gtk_widget_set_size_request (label_id2, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_id2), TRUE);

  label_prenom2 = gtk_label_new (_("Pr\303\251nom:"));
  gtk_widget_show (label_prenom2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_prenom2, 350, 96);
  gtk_widget_set_size_request (label_prenom2, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_prenom2), TRUE);

  label_nom2 = gtk_label_new (_("Nom:"));
  gtk_widget_show (label_nom2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_nom2, 350, 56);
  gtk_widget_set_size_request (label_nom2, 165, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_nom2), TRUE);

  label148 = gtk_label_new (_("jj/mm/aaaa"));
  gtk_widget_show (label148);
  gtk_fixed_put (GTK_FIXED (fixed3), label148, 704, 216);
  gtk_widget_set_size_request (label148, 122, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label148), TRUE);

  combobox_type_chambre2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_type_chambre2);
  gtk_fixed_put (GTK_FIXED (fixed3), combobox_type_chambre2, 518, 416);
  gtk_widget_set_size_request (combobox_type_chambre2, 304, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_type_chambre2), _("Chambre_\303\240_1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_type_chambre2), _("Chambre_\303\240_2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_type_chambre2), _("Chambre_\303\240_3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_type_chambre2), _("Chambre_\303\240_4"));

  label149 = gtk_label_new (_("jj/mm/aaaa"));
  gtk_widget_show (label149);
  gtk_fixed_put (GTK_FIXED (fixed3), label149, 704, 496);
  gtk_widget_set_size_request (label149, 122, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label149), TRUE);

  radiobutton_homme2 = gtk_radio_button_new_with_mnemonic (NULL, _("homme"));
  gtk_widget_show (radiobutton_homme2);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton_homme2, 520, 256);
  gtk_widget_set_size_request (radiobutton_homme2, 85, 30);
  gtk_button_set_focus_on_click (GTK_BUTTON (radiobutton_homme2), FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_homme2), radiobutton_homme2_group);
  radiobutton_homme2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_homme2));

  radiobutton_femme2 = gtk_radio_button_new_with_mnemonic (NULL, _("femme"));
  gtk_widget_show (radiobutton_femme2);
  gtk_fixed_put (GTK_FIXED (fixed3), radiobutton_femme2, 624, 256);
  gtk_widget_set_size_request (radiobutton_femme2, 85, 30);
  gtk_button_set_focus_on_click (GTK_BUTTON (radiobutton_femme2), FALSE);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_femme2), radiobutton_homme2_group);
  radiobutton_homme2_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_femme2));

  label150 = gtk_label_new (_("jj/mm/aaaa"));
  gtk_widget_show (label150);
  gtk_fixed_put (GTK_FIXED (fixed3), label150, 704, 536);
  gtk_widget_set_size_request (label150, 122, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label150), TRUE);

  button_afficher_modification = gtk_button_new ();
  gtk_widget_show (button_afficher_modification);
  gtk_fixed_put (GTK_FIXED (fixed3), button_afficher_modification, 565, 655);
  gtk_widget_set_size_request (button_afficher_modification, 84, 35);
  gtk_button_set_relief (GTK_BUTTON (button_afficher_modification), GTK_RELIEF_HALF);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_afficher_modification), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  label79 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label79);
  gtk_box_pack_start (GTK_BOX (hbox6), label79, FALSE, FALSE, 0);

  image6 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  button_retour_modification = gtk_button_new ();
  gtk_widget_show (button_retour_modification);
  gtk_fixed_put (GTK_FIXED (fixed3), button_retour_modification, 365, 655);
  gtk_widget_set_size_request (button_retour_modification, 84, 35);
  gtk_button_set_relief (GTK_BUTTON (button_retour_modification), GTK_RELIEF_HALF);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_retour_modification), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label78 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label78);
  gtk_box_pack_start (GTK_BOX (hbox5), label78, FALSE, FALSE, 0);

  label_modifie = gtk_label_new ("");
  gtk_widget_show (label_modifie);
  gtk_fixed_put (GTK_FIXED (fixed3), label_modifie, 536, 624);
  gtk_widget_set_size_request (label_modifie, 130, 30);

  quitter3 = gtk_button_new ();
  gtk_widget_show (quitter3);
  gtk_fixed_put (GTK_FIXED (fixed3), quitter3, 749, 655);
  gtk_widget_set_size_request (quitter3, 79, 35);
  gtk_button_set_relief (GTK_BUTTON (quitter3), GTK_RELIEF_HALF);
  gtk_button_set_focus_on_click (GTK_BUTTON (quitter3), FALSE);

  alignment29 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment29);
  gtk_container_add (GTK_CONTAINER (quitter3), alignment29);

  hbox29 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (alignment29), hbox29);

  label166 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label166);
  gtk_box_pack_start (GTK_BOX (hbox29), label166, FALSE, FALSE, 0);

  image36 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_box_pack_start (GTK_BOX (hbox29), image36, FALSE, FALSE, 0);

  label_mail_manquant2 = gtk_label_new ("");
  gtk_widget_show (label_mail_manquant2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_mail_manquant2, 824, 336);
  gtk_widget_set_size_request (label_mail_manquant2, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_mail_manquant2), TRUE);

  label_adresse_manquant2 = gtk_label_new ("");
  gtk_widget_show (label_adresse_manquant2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_adresse_manquant2, 824, 376);
  gtk_widget_set_size_request (label_adresse_manquant2, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_adresse_manquant2), TRUE);

  label_type_chambre_manquant2 = gtk_label_new ("");
  gtk_widget_show (label_type_chambre_manquant2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_type_chambre_manquant2, 824, 416);
  gtk_widget_set_size_request (label_type_chambre_manquant2, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_type_chambre_manquant2), TRUE);

  label_numero_chambre_manquant2 = gtk_label_new ("");
  gtk_widget_show (label_numero_chambre_manquant2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_numero_chambre_manquant2, 824, 456);
  gtk_widget_set_size_request (label_numero_chambre_manquant2, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_numero_chambre_manquant2), TRUE);

  label_debut_sejour_manquant2 = gtk_label_new ("");
  gtk_widget_show (label_debut_sejour_manquant2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_debut_sejour_manquant2, 824, 496);
  gtk_widget_set_size_request (label_debut_sejour_manquant2, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_debut_sejour_manquant2), TRUE);

  label_fin_sejour_manquant2 = gtk_label_new ("");
  gtk_widget_show (label_fin_sejour_manquant2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_fin_sejour_manquant2, 824, 536);
  gtk_widget_set_size_request (label_fin_sejour_manquant2, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_fin_sejour_manquant2), TRUE);

  label_existe_modification = gtk_label_new ("");
  gtk_widget_show (label_existe_modification);
  gtk_fixed_put (GTK_FIXED (fixed3), label_existe_modification, 824, 136);
  gtk_widget_set_size_request (label_existe_modification, 106, 30);

  label_nom_manquant2 = gtk_label_new ("");
  gtk_widget_show (label_nom_manquant2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_nom_manquant2, 824, 56);
  gtk_widget_set_size_request (label_nom_manquant2, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_nom_manquant2), TRUE);

  label_prenom_manquant2 = gtk_label_new ("");
  gtk_widget_show (label_prenom_manquant2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_prenom_manquant2, 824, 96);
  gtk_widget_set_size_request (label_prenom_manquant2, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_prenom_manquant2), TRUE);

  label_id_manquant2 = gtk_label_new ("");
  gtk_widget_show (label_id_manquant2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_id_manquant2, 824, 136);
  gtk_widget_set_size_request (label_id_manquant2, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_id_manquant2), TRUE);

  label_niveau_manquant2 = gtk_label_new ("");
  gtk_widget_show (label_niveau_manquant2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_niveau_manquant2, 824, 176);
  gtk_widget_set_size_request (label_niveau_manquant2, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_niveau_manquant2), TRUE);

  label_naissance_manquant2 = gtk_label_new ("");
  gtk_widget_show (label_naissance_manquant2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_naissance_manquant2, 824, 216);
  gtk_widget_set_size_request (label_naissance_manquant2, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_naissance_manquant2), TRUE);

  label_sexe_manquant2 = gtk_label_new ("");
  gtk_widget_show (label_sexe_manquant2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_sexe_manquant2, 824, 256);
  gtk_widget_set_size_request (label_sexe_manquant2, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_sexe_manquant2), TRUE);

  label_telephone_manquant2 = gtk_label_new ("");
  gtk_widget_show (label_telephone_manquant2);
  gtk_fixed_put (GTK_FIXED (fixed3), label_telephone_manquant2, 824, 296);
  gtk_widget_set_size_request (label_telephone_manquant2, 205, 30);
  gtk_label_set_line_wrap (GTK_LABEL (label_telephone_manquant2), TRUE);

  button_modifier = gtk_button_new ();
  gtk_widget_show (button_modifier);
  gtk_fixed_put (GTK_FIXED (fixed3), button_modifier, 555, 587);
  gtk_widget_set_size_request (button_modifier, 100, 40);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button_modifier), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  label144 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label144);
  gtk_box_pack_start (GTK_BOX (hbox20), label144, FALSE, FALSE, 0);

  image22 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox20), image22, FALSE, FALSE, 0);

  label_confirmer = gtk_label_new ("");
  gtk_widget_show (label_confirmer);
  gtk_fixed_put (GTK_FIXED (fixed3), label_confirmer, 672, 593);
  gtk_widget_set_size_request (label_confirmer, 232, 32);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton1, 424, 592);
  gtk_widget_set_size_request (checkbutton1, 100, 34);

  g_signal_connect ((gpointer) button_afficher_modification, "clicked",
                    G_CALLBACK (on_button_afficher_modification_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_modification, "clicked",
                    G_CALLBACK (on_button_retour_modification_clicked),
                    NULL);
  g_signal_connect ((gpointer) quitter3, "clicked",
                    G_CALLBACK (on_quitter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier, "clicked",
                    G_CALLBACK (on_button_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_modification, window_modification, "window_modification");
  GLADE_HOOKUP_OBJECT (window_modification, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window_modification, entry_nom2, "entry_nom2");
  GLADE_HOOKUP_OBJECT (window_modification, entry_prenom2, "entry_prenom2");
  GLADE_HOOKUP_OBJECT (window_modification, entry_id2, "entry_id2");
  GLADE_HOOKUP_OBJECT (window_modification, entry_adresse2, "entry_adresse2");
  GLADE_HOOKUP_OBJECT (window_modification, entry_telephone2, "entry_telephone2");
  GLADE_HOOKUP_OBJECT (window_modification, entry_mail2, "entry_mail2");
  GLADE_HOOKUP_OBJECT (window_modification, spinbutton_niveau2, "spinbutton_niveau2");
  GLADE_HOOKUP_OBJECT (window_modification, entry_numero_chambre2, "entry_numero_chambre2");
  GLADE_HOOKUP_OBJECT (window_modification, entry_debut_sejour2, "entry_debut_sejour2");
  GLADE_HOOKUP_OBJECT (window_modification, entry_fin_sejour2, "entry_fin_sejour2");
  GLADE_HOOKUP_OBJECT (window_modification, entry_naissance2, "entry_naissance2");
  GLADE_HOOKUP_OBJECT (window_modification, label_remplir_modification, "label_remplir_modification");
  GLADE_HOOKUP_OBJECT (window_modification, label_fin_sejour2, "label_fin_sejour2");
  GLADE_HOOKUP_OBJECT (window_modification, label_debut_sejour2, "label_debut_sejour2");
  GLADE_HOOKUP_OBJECT (window_modification, label_numero_chambre2, "label_numero_chambre2");
  GLADE_HOOKUP_OBJECT (window_modification, label_type_chambre2, "label_type_chambre2");
  GLADE_HOOKUP_OBJECT (window_modification, label_adresse2, "label_adresse2");
  GLADE_HOOKUP_OBJECT (window_modification, label_mail2, "label_mail2");
  GLADE_HOOKUP_OBJECT (window_modification, label_telephone2, "label_telephone2");
  GLADE_HOOKUP_OBJECT (window_modification, label_sexe2, "label_sexe2");
  GLADE_HOOKUP_OBJECT (window_modification, label_naissance2, "label_naissance2");
  GLADE_HOOKUP_OBJECT (window_modification, label_niveau2, "label_niveau2");
  GLADE_HOOKUP_OBJECT (window_modification, label_id2, "label_id2");
  GLADE_HOOKUP_OBJECT (window_modification, label_prenom2, "label_prenom2");
  GLADE_HOOKUP_OBJECT (window_modification, label_nom2, "label_nom2");
  GLADE_HOOKUP_OBJECT (window_modification, label148, "label148");
  GLADE_HOOKUP_OBJECT (window_modification, combobox_type_chambre2, "combobox_type_chambre2");
  GLADE_HOOKUP_OBJECT (window_modification, label149, "label149");
  GLADE_HOOKUP_OBJECT (window_modification, radiobutton_homme2, "radiobutton_homme2");
  GLADE_HOOKUP_OBJECT (window_modification, radiobutton_femme2, "radiobutton_femme2");
  GLADE_HOOKUP_OBJECT (window_modification, label150, "label150");
  GLADE_HOOKUP_OBJECT (window_modification, button_afficher_modification, "button_afficher_modification");
  GLADE_HOOKUP_OBJECT (window_modification, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window_modification, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window_modification, label79, "label79");
  GLADE_HOOKUP_OBJECT (window_modification, image6, "image6");
  GLADE_HOOKUP_OBJECT (window_modification, button_retour_modification, "button_retour_modification");
  GLADE_HOOKUP_OBJECT (window_modification, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window_modification, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window_modification, image5, "image5");
  GLADE_HOOKUP_OBJECT (window_modification, label78, "label78");
  GLADE_HOOKUP_OBJECT (window_modification, label_modifie, "label_modifie");
  GLADE_HOOKUP_OBJECT (window_modification, quitter3, "quitter3");
  GLADE_HOOKUP_OBJECT (window_modification, alignment29, "alignment29");
  GLADE_HOOKUP_OBJECT (window_modification, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (window_modification, label166, "label166");
  GLADE_HOOKUP_OBJECT (window_modification, image36, "image36");
  GLADE_HOOKUP_OBJECT (window_modification, label_mail_manquant2, "label_mail_manquant2");
  GLADE_HOOKUP_OBJECT (window_modification, label_adresse_manquant2, "label_adresse_manquant2");
  GLADE_HOOKUP_OBJECT (window_modification, label_type_chambre_manquant2, "label_type_chambre_manquant2");
  GLADE_HOOKUP_OBJECT (window_modification, label_numero_chambre_manquant2, "label_numero_chambre_manquant2");
  GLADE_HOOKUP_OBJECT (window_modification, label_debut_sejour_manquant2, "label_debut_sejour_manquant2");
  GLADE_HOOKUP_OBJECT (window_modification, label_fin_sejour_manquant2, "label_fin_sejour_manquant2");
  GLADE_HOOKUP_OBJECT (window_modification, label_existe_modification, "label_existe_modification");
  GLADE_HOOKUP_OBJECT (window_modification, label_nom_manquant2, "label_nom_manquant2");
  GLADE_HOOKUP_OBJECT (window_modification, label_prenom_manquant2, "label_prenom_manquant2");
  GLADE_HOOKUP_OBJECT (window_modification, label_id_manquant2, "label_id_manquant2");
  GLADE_HOOKUP_OBJECT (window_modification, label_niveau_manquant2, "label_niveau_manquant2");
  GLADE_HOOKUP_OBJECT (window_modification, label_naissance_manquant2, "label_naissance_manquant2");
  GLADE_HOOKUP_OBJECT (window_modification, label_sexe_manquant2, "label_sexe_manquant2");
  GLADE_HOOKUP_OBJECT (window_modification, label_telephone_manquant2, "label_telephone_manquant2");
  GLADE_HOOKUP_OBJECT (window_modification, button_modifier, "button_modifier");
  GLADE_HOOKUP_OBJECT (window_modification, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window_modification, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window_modification, label144, "label144");
  GLADE_HOOKUP_OBJECT (window_modification, image22, "image22");
  GLADE_HOOKUP_OBJECT (window_modification, label_confirmer, "label_confirmer");
  GLADE_HOOKUP_OBJECT (window_modification, checkbutton1, "checkbutton1");

  return window_modification;
}

GtkWidget*
create_window_affichage (void)
{
  GtkWidget *window_affichage;
  GtkWidget *fixed7;
  GtkWidget *entry_rechercher;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview;
  GtkWidget *button_retour_recherche;
  GtkWidget *image32;
  GtkWidget *label151;
  GtkWidget *button_rechercher;
  GtkWidget *image10;
  GtkWidget *quitter4;
  GtkWidget *alignment30;
  GtkWidget *hbox30;
  GtkWidget *label167;
  GtkWidget *image37;
  GtkWidget *button_modifier0;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *label99;
  GtkWidget *image15;
  GtkWidget *button_retour_affichage;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image16;
  GtkWidget *label100;
  GtkWidget *button_supprimer;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *label98;
  GtkWidget *image14;
  GtkWidget *label_supprime;
  GtkWidget *label_selectionnez;
  GtkWidget *label_non_trouve;

  window_affichage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_affichage, 1213, 715);
  gtk_window_set_title (GTK_WINDOW (window_affichage), _("Liste  des \303\251tudiants"));
  gtk_window_set_position (GTK_WINDOW (window_affichage), GTK_WIN_POS_CENTER);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (window_affichage), fixed7);
  gtk_widget_set_size_request (fixed7, 163, 715);

  entry_rechercher = gtk_entry_new ();
  gtk_widget_show (entry_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed7), entry_rechercher, 978, 8);
  gtk_widget_set_size_request (entry_rechercher, 107, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_rechercher), 8226);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed7), scrolledwindow1, 0, 48);
  gtk_widget_set_size_request (scrolledwindow1, 1213, 560);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  treeview = gtk_tree_view_new ();
  gtk_widget_show (treeview);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview);
  gtk_widget_set_size_request (treeview, 1213, 560);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview), TRUE);
  gtk_tree_view_set_hover_expand (GTK_TREE_VIEW (treeview), TRUE);

  button_retour_recherche = gtk_button_new ();
  gtk_fixed_put (GTK_FIXED (fixed7), button_retour_recherche, 910, 6);
  gtk_widget_set_size_request (button_retour_recherche, 40, 30);
  gtk_button_set_relief (GTK_BUTTON (button_retour_recherche), GTK_RELIEF_NONE);

  image32 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image32);
  gtk_container_add (GTK_CONTAINER (button_retour_recherche), image32);

  label151 = gtk_label_new (_("ID:"));
  gtk_widget_show (label151);
  gtk_fixed_put (GTK_FIXED (fixed7), label151, 953, 8);
  gtk_widget_set_size_request (label151, 24, 30);

  button_rechercher = gtk_button_new ();
  gtk_widget_show (button_rechercher);
  gtk_fixed_put (GTK_FIXED (fixed7), button_rechercher, 1084, 8);
  gtk_widget_set_size_request (button_rechercher, 45, 30);

  image10 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_container_add (GTK_CONTAINER (button_rechercher), image10);

  quitter4 = gtk_button_new ();
  gtk_widget_show (quitter4);
  gtk_fixed_put (GTK_FIXED (fixed7), quitter4, 838, 632);
  gtk_widget_set_size_request (quitter4, 120, 40);
  gtk_button_set_focus_on_click (GTK_BUTTON (quitter4), FALSE);

  alignment30 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment30);
  gtk_container_add (GTK_CONTAINER (quitter4), alignment30);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment30), hbox30);

  label167 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label167);
  gtk_box_pack_start (GTK_BOX (hbox30), label167, FALSE, FALSE, 3);

  image37 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image37);
  gtk_box_pack_start (GTK_BOX (hbox30), image37, FALSE, FALSE, 8);

  button_modifier0 = gtk_button_new ();
  gtk_widget_show (button_modifier0);
  gtk_fixed_put (GTK_FIXED (fixed7), button_modifier0, 510, 632);
  gtk_widget_set_size_request (button_modifier0, 120, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_modifier0), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  label99 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label99);
  gtk_box_pack_start (GTK_BOX (hbox14), label99, FALSE, FALSE, 0);

  image15 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox14), image15, FALSE, FALSE, 6);

  button_retour_affichage = gtk_button_new ();
  gtk_widget_show (button_retour_affichage);
  gtk_fixed_put (GTK_FIXED (fixed7), button_retour_affichage, 350, 632);
  gtk_widget_set_size_request (button_retour_affichage, 120, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_retour_affichage), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox15), image16, FALSE, FALSE, 5);

  label100 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label100);
  gtk_box_pack_start (GTK_BOX (hbox15), label100, FALSE, FALSE, 0);

  button_supprimer = gtk_button_new ();
  gtk_widget_show (button_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed7), button_supprimer, 670, 632);
  gtk_widget_set_size_request (button_supprimer, 120, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_supprimer), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  label98 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label98);
  gtk_box_pack_start (GTK_BOX (hbox13), label98, FALSE, FALSE, 0);

  image14 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox13), image14, FALSE, FALSE, 2);

  label_supprime = gtk_label_new ("");
  gtk_widget_show (label_supprime);
  gtk_fixed_put (GTK_FIXED (fixed7), label_supprime, 666, 672);
  gtk_widget_set_size_request (label_supprime, 138, 40);

  label_selectionnez = gtk_label_new ("");
  gtk_widget_show (label_selectionnez);
  gtk_fixed_put (GTK_FIXED (fixed7), label_selectionnez, 506, 672);
  gtk_widget_set_size_request (label_selectionnez, 285, 40);

  label_non_trouve = gtk_label_new ("");
  gtk_widget_show (label_non_trouve);
  gtk_fixed_put (GTK_FIXED (fixed7), label_non_trouve, 1128, 8);
  gtk_widget_set_size_request (label_non_trouve, 84, 30);

  g_signal_connect ((gpointer) entry_rechercher, "activate",
                    G_CALLBACK (on_entry_rechercher_activate),
                    NULL);
  g_signal_connect ((gpointer) entry_rechercher, "delete_text",
                    G_CALLBACK (on_entry_rechercher_delete_text),
                    NULL);
  g_signal_connect ((gpointer) button_retour_recherche, "clicked",
                    G_CALLBACK (on_button_retour_recherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_rechercher, "clicked",
                    G_CALLBACK (on_button_rechercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) quitter4, "clicked",
                    G_CALLBACK (on_quitter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier0, "clicked",
                    G_CALLBACK (on_button_modifier0_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_affichage, "clicked",
                    G_CALLBACK (on_button_retour_affichage_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer, "clicked",
                    G_CALLBACK (on_button_supprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_affichage, window_affichage, "window_affichage");
  GLADE_HOOKUP_OBJECT (window_affichage, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (window_affichage, entry_rechercher, "entry_rechercher");
  GLADE_HOOKUP_OBJECT (window_affichage, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window_affichage, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (window_affichage, button_retour_recherche, "button_retour_recherche");
  GLADE_HOOKUP_OBJECT (window_affichage, image32, "image32");
  GLADE_HOOKUP_OBJECT (window_affichage, label151, "label151");
  GLADE_HOOKUP_OBJECT (window_affichage, button_rechercher, "button_rechercher");
  GLADE_HOOKUP_OBJECT (window_affichage, image10, "image10");
  GLADE_HOOKUP_OBJECT (window_affichage, quitter4, "quitter4");
  GLADE_HOOKUP_OBJECT (window_affichage, alignment30, "alignment30");
  GLADE_HOOKUP_OBJECT (window_affichage, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (window_affichage, label167, "label167");
  GLADE_HOOKUP_OBJECT (window_affichage, image37, "image37");
  GLADE_HOOKUP_OBJECT (window_affichage, button_modifier0, "button_modifier0");
  GLADE_HOOKUP_OBJECT (window_affichage, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window_affichage, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window_affichage, label99, "label99");
  GLADE_HOOKUP_OBJECT (window_affichage, image15, "image15");
  GLADE_HOOKUP_OBJECT (window_affichage, button_retour_affichage, "button_retour_affichage");
  GLADE_HOOKUP_OBJECT (window_affichage, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window_affichage, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window_affichage, image16, "image16");
  GLADE_HOOKUP_OBJECT (window_affichage, label100, "label100");
  GLADE_HOOKUP_OBJECT (window_affichage, button_supprimer, "button_supprimer");
  GLADE_HOOKUP_OBJECT (window_affichage, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (window_affichage, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window_affichage, label98, "label98");
  GLADE_HOOKUP_OBJECT (window_affichage, image14, "image14");
  GLADE_HOOKUP_OBJECT (window_affichage, label_supprime, "label_supprime");
  GLADE_HOOKUP_OBJECT (window_affichage, label_selectionnez, "label_selectionnez");
  GLADE_HOOKUP_OBJECT (window_affichage, label_non_trouve, "label_non_trouve");

  return window_affichage;
}

GtkWidget*
create_confirmer_supprission (void)
{
  GtkWidget *confirmer_supprission;
  GtkWidget *fixed12;
  GtkWidget *hseparator6;
  GtkWidget *label156;
  GtkWidget *confirmer_supp;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *label157;
  GtkWidget *image25;
  GtkWidget *annuler_supp;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image26;
  GtkWidget *label158;

  confirmer_supprission = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (confirmer_supprission), _(" "));
  gtk_window_set_position (GTK_WINDOW (confirmer_supprission), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (confirmer_supprission), FALSE);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (confirmer_supprission), fixed12);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_show (hseparator6);
  gtk_fixed_put (GTK_FIXED (fixed12), hseparator6, 8, 128);
  gtk_widget_set_size_request (hseparator6, 336, 16);

  label156 = gtk_label_new (_("Vous-\303\252tes sur le point de supprimer cet \303\251tudiant!"));
  gtk_widget_show (label156);
  gtk_fixed_put (GTK_FIXED (fixed12), label156, 0, 24);
  gtk_widget_set_size_request (label156, 355, 17);

  confirmer_supp = gtk_button_new ();
  gtk_widget_show (confirmer_supp);
  gtk_fixed_put (GTK_FIXED (fixed12), confirmer_supp, 70, 72);
  gtk_widget_set_size_request (confirmer_supp, 100, 30);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (confirmer_supp), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  label157 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label157);
  gtk_box_pack_start (GTK_BOX (hbox23), label157, FALSE, FALSE, 0);

  image25 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox23), image25, FALSE, FALSE, 0);

  annuler_supp = gtk_button_new ();
  gtk_widget_show (annuler_supp);
  gtk_fixed_put (GTK_FIXED (fixed12), annuler_supp, 205, 72);
  gtk_widget_set_size_request (annuler_supp, 100, 30);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (annuler_supp), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image26 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox24), image26, FALSE, FALSE, 0);

  label158 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label158);
  gtk_box_pack_start (GTK_BOX (hbox24), label158, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) confirmer_supp, "clicked",
                    G_CALLBACK (on_confirmer_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler_supp, "clicked",
                    G_CALLBACK (on_annuler_supp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (confirmer_supprission, confirmer_supprission, "confirmer_supprission");
  GLADE_HOOKUP_OBJECT (confirmer_supprission, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (confirmer_supprission, hseparator6, "hseparator6");
  GLADE_HOOKUP_OBJECT (confirmer_supprission, label156, "label156");
  GLADE_HOOKUP_OBJECT (confirmer_supprission, confirmer_supp, "confirmer_supp");
  GLADE_HOOKUP_OBJECT (confirmer_supprission, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (confirmer_supprission, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (confirmer_supprission, label157, "label157");
  GLADE_HOOKUP_OBJECT (confirmer_supprission, image25, "image25");
  GLADE_HOOKUP_OBJECT (confirmer_supprission, annuler_supp, "annuler_supp");
  GLADE_HOOKUP_OBJECT (confirmer_supprission, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (confirmer_supprission, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (confirmer_supprission, image26, "image26");
  GLADE_HOOKUP_OBJECT (confirmer_supprission, label158, "label158");

  return confirmer_supprission;
}

GtkWidget*
create_confirmer_modification (void)
{
  GtkWidget *confirmer_modification;
  GtkWidget *fixed13;
  GtkWidget *hseparator7;
  GtkWidget *label159;
  GtkWidget *confirmer_modif;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *label160;
  GtkWidget *image27;
  GtkWidget *annuler_modif;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image28;
  GtkWidget *label161;

  confirmer_modification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (confirmer_modification), _(" "));
  gtk_window_set_position (GTK_WINDOW (confirmer_modification), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (confirmer_modification), FALSE);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (confirmer_modification), fixed13);

  hseparator7 = gtk_hseparator_new ();
  gtk_widget_show (hseparator7);
  gtk_fixed_put (GTK_FIXED (fixed13), hseparator7, 10, 128);
  gtk_widget_set_size_request (hseparator7, 336, 16);

  label159 = gtk_label_new (_("Faire des modification sur les informations reli\303\251es \303\240 cet \303\251tudiant, continuer?"));
  gtk_widget_show (label159);
  gtk_fixed_put (GTK_FIXED (fixed13), label159, 8, 0);
  gtk_widget_set_size_request (label159, 347, 56);
  gtk_label_set_justify (GTK_LABEL (label159), GTK_JUSTIFY_CENTER);
  gtk_label_set_line_wrap (GTK_LABEL (label159), TRUE);

  confirmer_modif = gtk_button_new ();
  gtk_widget_show (confirmer_modif);
  gtk_fixed_put (GTK_FIXED (fixed13), confirmer_modif, 88, 72);
  gtk_widget_set_size_request (confirmer_modif, 80, 30);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (confirmer_modif), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  label160 = gtk_label_new_with_mnemonic (_("Oui"));
  gtk_widget_show (label160);
  gtk_box_pack_start (GTK_BOX (hbox25), label160, FALSE, FALSE, 0);

  image27 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox25), image27, FALSE, FALSE, 5);

  annuler_modif = gtk_button_new ();
  gtk_widget_show (annuler_modif);
  gtk_fixed_put (GTK_FIXED (fixed13), annuler_modif, 205, 72);
  gtk_widget_set_size_request (annuler_modif, 80, 30);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (annuler_modif), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image28 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox26), image28, FALSE, FALSE, 4);

  label161 = gtk_label_new_with_mnemonic (_("Non"));
  gtk_widget_show (label161);
  gtk_box_pack_start (GTK_BOX (hbox26), label161, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) confirmer_modif, "clicked",
                    G_CALLBACK (on_confirmer_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler_modif, "clicked",
                    G_CALLBACK (on_annuler_modif_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (confirmer_modification, confirmer_modification, "confirmer_modification");
  GLADE_HOOKUP_OBJECT (confirmer_modification, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (confirmer_modification, hseparator7, "hseparator7");
  GLADE_HOOKUP_OBJECT (confirmer_modification, label159, "label159");
  GLADE_HOOKUP_OBJECT (confirmer_modification, confirmer_modif, "confirmer_modif");
  GLADE_HOOKUP_OBJECT (confirmer_modification, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (confirmer_modification, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (confirmer_modification, label160, "label160");
  GLADE_HOOKUP_OBJECT (confirmer_modification, image27, "image27");
  GLADE_HOOKUP_OBJECT (confirmer_modification, annuler_modif, "annuler_modif");
  GLADE_HOOKUP_OBJECT (confirmer_modification, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (confirmer_modification, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (confirmer_modification, image28, "image28");
  GLADE_HOOKUP_OBJECT (confirmer_modification, label161, "label161");

  return confirmer_modification;
}

GtkWidget*
create_window_quitter (void)
{
  GtkWidget *window_quitter;
  GtkWidget *fixed14;
  GtkWidget *hseparator8;
  GtkWidget *label168;
  GtkWidget *annuler_quitter;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image39;
  GtkWidget *label170;
  GtkWidget *confirmer_quitter;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *label169;
  GtkWidget *image38;

  window_quitter = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_quitter), _(" "));
  gtk_window_set_position (GTK_WINDOW (window_quitter), GTK_WIN_POS_CENTER);
  gtk_window_set_resizable (GTK_WINDOW (window_quitter), FALSE);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (window_quitter), fixed14);

  hseparator8 = gtk_hseparator_new ();
  gtk_widget_show (hseparator8);
  gtk_fixed_put (GTK_FIXED (fixed14), hseparator8, 8, 128);
  gtk_widget_set_size_request (hseparator8, 336, 16);

  label168 = gtk_label_new (_("   \303\212tes-vous s\303\273r de vouloir quitter?"));
  gtk_widget_show (label168);
  gtk_fixed_put (GTK_FIXED (fixed14), label168, 0, 24);
  gtk_widget_set_size_request (label168, 355, 17);

  annuler_quitter = gtk_button_new ();
  gtk_widget_show (annuler_quitter);
  gtk_fixed_put (GTK_FIXED (fixed14), annuler_quitter, 205, 72);
  gtk_widget_set_size_request (annuler_quitter, 100, 30);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (annuler_quitter), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image39 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_box_pack_start (GTK_BOX (hbox32), image39, FALSE, FALSE, 0);

  label170 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label170);
  gtk_box_pack_start (GTK_BOX (hbox32), label170, FALSE, FALSE, 0);

  confirmer_quitter = gtk_button_new ();
  gtk_widget_show (confirmer_quitter);
  gtk_fixed_put (GTK_FIXED (fixed14), confirmer_quitter, 70, 72);
  gtk_widget_set_size_request (confirmer_quitter, 100, 30);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (confirmer_quitter), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  label169 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label169);
  gtk_box_pack_start (GTK_BOX (hbox31), label169, FALSE, FALSE, 0);

  image38 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image38);
  gtk_box_pack_start (GTK_BOX (hbox31), image38, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) annuler_quitter, "clicked",
                    G_CALLBACK (on_annuler_quitter_clicked),
                    NULL);
  g_signal_connect ((gpointer) confirmer_quitter, "clicked",
                    G_CALLBACK (on_confirmer_quitter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_quitter, window_quitter, "window_quitter");
  GLADE_HOOKUP_OBJECT (window_quitter, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (window_quitter, hseparator8, "hseparator8");
  GLADE_HOOKUP_OBJECT (window_quitter, label168, "label168");
  GLADE_HOOKUP_OBJECT (window_quitter, annuler_quitter, "annuler_quitter");
  GLADE_HOOKUP_OBJECT (window_quitter, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (window_quitter, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (window_quitter, image39, "image39");
  GLADE_HOOKUP_OBJECT (window_quitter, label170, "label170");
  GLADE_HOOKUP_OBJECT (window_quitter, confirmer_quitter, "confirmer_quitter");
  GLADE_HOOKUP_OBJECT (window_quitter, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (window_quitter, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (window_quitter, label169, "label169");
  GLADE_HOOKUP_OBJECT (window_quitter, image38, "image38");

  return window_quitter;
}

