/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window_gestion (void);
GtkWidget* create_window_ajout (void);
GtkWidget* create_window_modification (void);
GtkWidget* create_window_affichage (void);
GtkWidget* create_confirmer_supprission (void);
GtkWidget* create_confirmer_modification (void);
GtkWidget* create_window_quitter (void);
